# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4e3be177e812481b39b42b2d64d782141fa3e2ab115569f4700ee3fa2e539ad55dcaac04c7dfa86194987222e052de1e6c6f5c034031d6cadbf1c555497a47

test:
  secret_key_base: 823e446e8ca65be361c197731c8c0c31318742727f3d35a64758e56a450b58824f904eaa7fff9042045a8645bb62c3820151633b41fee458574172bb579bf6a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
